package com.michalbykowy.iotsim.api;

import java.time.Instant;

/**
 * Standardized data transfer object for reporting API errors to the client.
 * <p>
 * This record ensures a consistent JSON structure for all HTTP error responses
 * (4xx and 5xx) generated by the global exception handler.
 * </p>
 *
 * @param statusCode The HTTP status code (e.g., 400, 404, 500).
 * @param message    A descriptive message explaining the reason for the error.
 * @param path       The URI path of the request that caused the error.
 * @param timestamp  The UTC timestamp when the error occurred.
 */
public record ErrorResponse(
        int statusCode,
        String message,
        String path,
        Instant timestamp
) {}